### ISSUE TITLE
Consider decoupling the file size from the page size

### ISSUE THREAD

**Issue by stuaxo** [uktrade/sqlite-s3vfs#10]
This may be a documentation issue, or implementation may be needed

From the docs:
```
Block size and page size

SQLite writes data in pages, which are 4096 bytes by default. sqlite-s3vfs stores data in blocks, which are also 4096 bytes by default. If you change one you should change the other to match for performance reasons.
```

4096 is a good number locally, it matches the default memory page size on Linux and Windows and the block size on ext3/4 filesystems.

On s3 or http generally 4096 seems small as the overhead of each request will be a large % of the time, and less http requests is probably optimal.

Q:  Are block size and page size really coupled, or can block size be a multiple of page size and still be performant ?

If it's fine as a multiple, can the docs be updated to mention this ?

Action:

Consider recommending a larger block size (may need testing to find an optimal size, but the 65536 from the docs doesn't seem like a bad start).

It may be worth using uktrade/tamato to run these tests as it is a user of sqlite-s3vfs.

**Comment by simonwo** [comment]
For every page write it will require an incremental upload to S3. So if your page size is 1/4 of the block size, you will need 4 writes, most of which will just be the same data. 

tamato uses the maximum block size, but we haven't done any specific performance tuning on that.

**Comment by michalc** [comment]
On this, I suspect there are loads of ways of making things more performant, but I think from TaMaTo's point of view, things are fast enough(?), and most ways I (and from what I read above, you?) can think of making it more performant introduces complexity. So at the moment, I'm probably a bit anti, since there would be risk of bugs for no real benefit...

> Consider recommending a larger block size (may need testing to find an optimal size, but the 65536 from the docs doesn't seem like a bad start).

And on this, I did consider explicitly recommending a larger block size, but I guess didn't really want to spend time testing, and I wonder if it's dependant on usage patterns. Maybe 4k is better than 65k for some cases, and 65k better for others?

**Comment by stuaxo** [comment]
There's no specific need from tamato at this time*, it's more that I enjoy making things faster.

Though it's quite possibly because we haven't been looking, benchmarking is definitely something we will look into at some point.
